# Generated by Django 3.2 on 2022-12-03 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skincare',
            options={'ordering': ['rating'], 'verbose_name': 'Skincare Product'},
        ),
        migrations.AddField(
            model_name='skintype',
            name='slug',
            field=models.SlugField(max_length=200, null=True),
        ),
    ]
