# Generated by Django 3.2 on 2022-12-13 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0002_auto_20221213_2107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skincare',
            old_name='crultey_free',
            new_name='cruelty_free',
        ),
    ]
