# Generated by Django 3.2 on 2022-12-13 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skincare', '0003_rename_crultey_free_skincare_cruelty_free'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skincare',
            old_name='alchol_free',
            new_name='alcohol_free',
        ),
    ]
